 spring:
  security:
    oauth2:
      client:
        registration:
          github:
            client-id: ${github.application.client.id}
            client-secret: ${github.application.client.secret}